name: super_anuncio
description: Super Anúncio - análise inteligente de anúncios da Shopee.
publish_to: 'none'
version: 1.5.4+14

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.0
  shared_preferences: ^2.5.3
  pdf: ^3.11.3
  audioplayers: ^6.5.1

flutter:
  uses-material-design: true
