name: super_anuncio
description: Super Anúncio - análise inteligente de anúncios da Shopee.
publish_to: 'none'
version: 1.4.2+6

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.0

flutter:
  uses-material-design: true
